controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# app_location:
task_report:
    path: /task/report
    controller: App\Controller\TaskController::generateTaskReportAction
    